name: Python CI Build Test

permissions:
  contents: read
  actions: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v4

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x" #pulls the latest python 3 version
          cache: "pip"

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Emulator
        # pls note this job runs the emulator and handles timeout to force stop server so that the build doesnt run indefinitely
        run: |
          timeout 10s python3 startEmul.py 4 || code=$?
          if [ $code -eq 124 ]; then
            echo "Status: Server exited via timeout as expected"
          else
            echo "Failed with exit code $code"
            exit $code
          fi